<?php
/** Unified location profile: modules. @package Lealez */
if ( ! defined( 'ABSPATH' ) ) { exit; }

trait Lealez_Unified_Location_Modules_Trait {

    private function get_location_modules() {
        return array(
            'overview' => array(
                'label' => __( 'Resumen', 'lealez' ),
                'description' => __( 'Estado general del perfil', 'lealez' ),
                'long_description' => __( 'Revisa el diligenciamiento, la conexión con Google y los cambios pendientes.', 'lealez' ),
                'icon' => 'dashicons-dashboard',
                'group' => __( 'General', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => '',
            ),
            'internal' => array(
                'label' => __( 'Configuración interna', 'lealez' ),
                'description' => __( 'Empresa, lealtad y responsables', 'lealez' ),
                'long_description' => __( 'Datos de administración de Lealez que no se publican en Google.', 'lealez' ),
                'icon' => 'dashicons-admin-settings',
                'group' => __( 'General', 'lealez' ),
                'scope' => 'internal',
                'metabox_id' => '',
                'local_fields' => array(
                    __( 'Empresa propietaria y nombre interno de la ficha', 'lealez' ),
                    __( 'Código y estado interno', 'lealez' ),
                    __( 'Configuración de lealtad', 'lealez' ),
                    __( 'Responsable, teléfonos, correos y notas internas', 'lealez' ),
                ),
            ),
            'connection' => array(
                'label' => __( 'Conexión con Google', 'lealez' ),
                'description' => __( 'Estado de la vinculación', 'lealez' ),
                'long_description' => __( 'Consulta si esta ubicación está conectada y lista para sincronizar con Google Business Profile.', 'lealez' ),
                'icon' => 'dashicons-admin-links',
                'group' => __( 'General', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb',
                'business_admin_only' => true,
                'client_summary' => true,
                'read_only' => true,
                'read_fields' => array( __( 'Estado de conexión y verificación del perfil', 'lealez' ) ),
            ),
            'sync' => array(
                'label' => __( 'Sincronización', 'lealez' ),
                'description' => __( 'Actualizar y publicar cambios', 'lealez' ),
                'long_description' => __( 'Sincroniza la información disponible respetando el flujo de guardar primero en Lealez y publicar después en Google.', 'lealez' ),
                'icon' => 'dashicons-update',
                'group' => __( 'General', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => 'oy_gmb_integration_control',
                'business_admin_only' => true,
                'classic_save' => true,
            ),
            'basic' => array(
                'label' => __( 'Información básica', 'lealez' ),
                'description' => __( 'Descripción, apertura y categorías', 'lealez' ),
                'long_description' => __( 'Administra la información principal que identifica y describe públicamente esta ubicación.', 'lealez' ),
                'icon' => 'dashicons-info-outline',
                'group' => __( 'Información del perfil', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => 'oy_location_basic_info',
                'google_fields' => array(
                    __( 'Descripción del negocio', 'lealez' ),
                    __( 'Fecha de apertura', 'lealez' ),
                    __( 'Categoría principal y categorías adicionales seleccionadas desde Google', 'lealez' ),
                ),
                'local_fields' => array(
                    __( 'Rango de precios mientras no exista una publicación compatible para este campo', 'lealez' ),
                ),
            ),
            'address' => array(
                'label' => __( 'Dirección y cobertura', 'lealez' ),
                'description' => __( 'Dirección, áreas de servicio y mapa', 'lealez' ),
                'long_description' => __( 'Administra la dirección pública o las áreas donde prestas servicio y valida la ubicación antes de publicarla.', 'lealez' ),
                'icon' => 'dashicons-location',
                'group' => __( 'Información del perfil', 'lealez' ),
                'scope' => 'google_write',
                'metabox_id' => 'oy_location_address',
                'google_fields' => array(
                    __( 'Dirección y complemento', 'lealez' ),
                    __( 'Ciudad, región, país y código postal', 'lealez' ),
                    __( 'Áreas de servicio y visibilidad de la dirección', 'lealez' ),
                    __( 'Ubicación en el mapa', 'lealez' ),
                ),
            ),
            'contact' => array(
                'label' => __( 'Contacto y enlaces', 'lealez' ),
                'description' => __( 'Teléfonos, web, chat y acciones', 'lealez' ),
                'long_description' => __( 'Administra los canales públicos de contacto y los enlaces que Google admite para esta ubicación.', 'lealez' ),
                'icon' => 'dashicons-phone',
                'group' => __( 'Información del perfil', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => 'oy_location_contact',
                'google_fields' => array(
                    __( 'Teléfono principal y teléfonos adicionales', 'lealez' ),
                    __( 'Sitio web', 'lealez' ),
                    __( 'Chat, reservas, pedidos y enlaces de acción cuando estén disponibles', 'lealez' ),
                ),
                'local_fields' => array(
                    __( 'Redes sociales manuales y otros datos que Lealez conserve solo localmente', 'lealez' ),
                ),
            ),
            'hours' => array(
                'label' => __( 'Horarios', 'lealez' ),
                'description' => __( 'Horario regular y especial', 'lealez' ),
                'long_description' => __( 'Configura horarios normales y fechas especiales, guarda los cambios y publícalos en Google cuando estén listos.', 'lealez' ),
                'icon' => 'dashicons-clock',
                'group' => __( 'Información del perfil', 'lealez' ),
                'scope' => 'google_write',
                'metabox_id' => 'oy_location_hours',
                'google_fields' => array(
                    __( 'Horario regular, cierres y atención 24 horas', 'lealez' ),
                    __( 'Horarios especiales y excepciones por fecha', 'lealez' ),
                ),
            ),
            'attributes' => array(
                'label' => __( 'Características', 'lealez' ),
                'description' => __( 'Opciones disponibles según el negocio', 'lealez' ),
                'long_description' => __( 'Las características disponibles cambian según la categoría y el país. Lealez consulta a Google cuáles corresponden a esta ubicación antes de permitir su publicación.', 'lealez' ),
                'icon' => 'dashicons-yes-alt',
                'group' => __( 'Información del perfil', 'lealez' ),
                'scope' => 'google_write',
                'metabox_id' => 'oy_location_gmb_more_attrs',
                'google_fields' => array( __( 'Características habilitadas por Google para la categoría y el país de la ubicación', 'lealez' ) ),
            ),
            'media' => array(
                'label' => __( 'Fotos en Google', 'lealez' ),
                'description' => __( 'Contenido visual del perfil', 'lealez' ),
                'long_description' => __( 'Consulta las fotografías asociadas al perfil y revisa el contenido disponible en Google.', 'lealez' ),
                'icon' => 'dashicons-format-gallery',
                'group' => __( 'Contenido', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb_owner_media',
                'read_fields' => array( __( 'Fotos y categorías de contenido disponibles en Google', 'lealez' ) ),
            ),
            'menu' => array(
                'label' => __( 'Menú', 'lealez' ),
                'description' => __( 'Secciones, platos, precios y fotos', 'lealez' ),
                'long_description' => __( 'Este módulo aparece cuando la ubicación tiene un menú de alimentos aplicable. Guarda localmente antes de publicar los cambios.', 'lealez' ),
                'icon' => 'dashicons-food',
                'group' => __( 'Contenido', 'lealez' ),
                'scope' => 'google_write',
                'metabox_id' => 'oy_location_menu',
                'google_fields' => array( __( 'Secciones, platos, precios, descripciones y contenido compatible', 'lealez' ) ),
            ),
            'services' => array(
                'label' => __( 'Servicios', 'lealez' ),
                'description' => __( 'Catálogo aplicable a la categoría', 'lealez' ),
                'long_description' => __( 'Administra los servicios de la ubicación. Las opciones disponibles dependen de la categoría del negocio y de lo que Google admita para ese perfil.', 'lealez' ),
                'icon' => 'dashicons-store',
                'group' => __( 'Contenido', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => 'oy_location_products',
                'classic_save' => true,
                'read_fields' => array( __( 'Servicios disponibles en Google cuando la ubicación los admite', 'lealez' ) ),
                'local_fields' => array( __( 'Catálogo guardado en Lealez cuando Google no permite publicarlo directamente', 'lealez' ) ),
            ),
            'posts' => array(
                'label' => __( 'Publicaciones', 'lealez' ),
                'description' => __( 'Novedades y contenido', 'lealez' ),
                'long_description' => __( 'Consulta, crea, actualiza o elimina publicaciones del perfil de Google desde Lealez.', 'lealez' ),
                'icon' => 'dashicons-megaphone',
                'group' => __( 'Opiniones y actividad', 'lealez' ),
                'scope' => 'google_direct',
                'metabox_id' => 'oy_location_gmb_posts',
                'google_fields' => array( __( 'Publicaciones, llamadas a la acción, fechas y medios', 'lealez' ) ),
                'local_fields' => array( __( 'Borradores hasta que decidas publicarlos', 'lealez' ) ),
            ),
            'reviews' => array(
                'label' => __( 'Opiniones', 'lealez' ),
                'description' => __( 'Reseñas y respuestas', 'lealez' ),
                'long_description' => __( 'Consulta las reseñas de Google y responde desde el perfil de la ubicación.', 'lealez' ),
                'icon' => 'dashicons-star-filled',
                'group' => __( 'Opiniones y actividad', 'lealez' ),
                'scope' => 'google_direct',
                'metabox_id' => 'oy_location_gmb_reviews',
                'read_fields' => array( __( 'Calificaciones, comentarios y reseñas publicadas', 'lealez' ) ),
                'google_fields' => array( __( 'Respuestas del negocio', 'lealez' ) ),
            ),
            'performance' => array(
                'label' => __( 'Rendimiento', 'lealez' ),
                'description' => __( 'Métricas y comparativas', 'lealez' ),
                'long_description' => __( 'Consulta el rendimiento disponible del perfil y conserva comparativas históricas en Lealez.', 'lealez' ),
                'icon' => 'dashicons-chart-area',
                'group' => __( 'Resultados', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb_performance',
                'read_fields' => array( __( 'Visualizaciones, llamadas, clics, indicaciones, reservas y demás métricas disponibles', 'lealez' ) ),
                'local_fields' => array( __( 'Histórico guardado para comparaciones y reportes', 'lealez' ) ),
            ),
            'keywords' => array(
                'label' => __( 'Frases de búsqueda', 'lealez' ),
                'description' => __( 'Cómo encuentran tu negocio', 'lealez' ),
                'long_description' => __( 'Consulta las frases con las que las personas encontraron esta ubicación y guarda los resultados seleccionados.', 'lealez' ),
                'icon' => 'dashicons-search',
                'group' => __( 'Resultados', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb_keywords',
                'read_fields' => array( __( 'Frases e impresiones mensuales disponibles en Google', 'lealez' ) ),
                'local_fields' => array( __( 'Selección e histórico para reportes de Lealez', 'lealez' ) ),
            ),
            'busyhours' => array(
                'label' => __( 'Mayor interés', 'lealez' ),
                'description' => __( 'Tendencia por día y hora', 'lealez' ),
                'long_description' => __( 'Visualiza el patrón estimado de mayor interés a partir del rendimiento disponible de la ubicación.', 'lealez' ),
                'icon' => 'dashicons-chart-bar',
                'group' => __( 'Resultados', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb_busyhours',
                'read_fields' => array( __( 'Datos de rendimiento utilizados para calcular la tendencia', 'lealez' ) ),
                'local_fields' => array( __( 'Curva estimada guardada en Lealez', 'lealez' ) ),
            ),
        );
    }
}
