<?php
/** Unified location profile: modules. @package Lealez */
if ( ! defined( 'ABSPATH' ) ) { exit; }

trait Lealez_Unified_Location_Modules_Trait {

    private function get_location_modules() {
        return array(
            'overview' => array(
                'label' => __( 'Resumen', 'lealez' ),
                'description' => __( 'Estado general del perfil', 'lealez' ),
                'long_description' => __( 'Revisa la completitud de la ficha, la conexión con Google y los cambios que aún requieren atención.', 'lealez' ),
                'icon' => 'dashicons-dashboard',
                'group' => __( 'General', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => '',
            ),
            'internal' => array(
                'label' => __( 'Administración Lealez', 'lealez' ),
                'description' => __( 'Empresa, lealtad y responsables', 'lealez' ),
                'long_description' => __( 'Datos de operación interna de Lealez. Esta información no se publica en Google.', 'lealez' ),
                'icon' => 'dashicons-admin-settings',
                'group' => __( 'General', 'lealez' ),
                'scope' => 'internal',
                'metabox_id' => '',
                'local_fields' => array(
                    __( 'Empresa propietaria y nombre interno de la ficha', 'lealez' ),
                    __( 'Código y estado interno', 'lealez' ),
                    __( 'Configuración de lealtad', 'lealez' ),
                    __( 'Responsable, teléfonos, correos y notas internas', 'lealez' ),
                ),
            ),
            'basic' => array(
                'label' => __( 'Información del negocio', 'lealez' ),
                'description' => __( 'Descripción, apertura y categoría', 'lealez' ),
                'long_description' => __( 'Completa la información principal que los clientes reconocen en la ficha del negocio.', 'lealez' ),
                'icon' => 'dashicons-info-outline',
                'group' => __( 'Perfil público', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => 'oy_location_basic_info',
                'google_fields' => array(
                    __( 'Descripción pública de la empresa', 'lealez' ),
                    __( 'Fecha de apertura cuando corresponde', 'lealez' ),
                ),
                'local_fields' => array(
                    __( 'Categorías mientras Lealez no pueda garantizar una publicación segura de ese cambio', 'lealez' ),
                    __( 'Rango de precios', 'lealez' ),
                ),
            ),
            'address' => array(
                'label' => __( 'Ubicación y áreas de servicio', 'lealez' ),
                'description' => __( 'Dirección, cobertura y mapa', 'lealez' ),
                'long_description' => __( 'Configura la dirección visible o las áreas de servicio según el tipo de negocio. Lealez evita exigir una dirección física cuando la ficha funciona únicamente por cobertura.', 'lealez' ),
                'icon' => 'dashicons-location',
                'group' => __( 'Perfil público', 'lealez' ),
                'scope' => 'google_write',
                'metabox_id' => 'oy_location_address',
                'google_fields' => array(
                    __( 'Dirección y complemento cuando el negocio recibe clientes', 'lealez' ),
                    __( 'Ciudad, región, país y código postal', 'lealez' ),
                    __( 'Áreas de servicio y visibilidad de la dirección', 'lealez' ),
                    __( 'Ubicación en el mapa cuando aplica', 'lealez' ),
                ),
            ),
            'contact' => array(
                'label' => __( 'Contacto y acciones', 'lealez' ),
                'description' => __( 'Teléfonos, web, reservas y pedidos', 'lealez' ),
                'long_description' => __( 'Administra los canales públicos disponibles para que los clientes llamen, visiten tu sitio o realicen acciones compatibles.', 'lealez' ),
                'icon' => 'dashicons-phone',
                'group' => __( 'Perfil público', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => 'oy_location_contact',
                'google_fields' => array(
                    __( 'Teléfono principal y teléfonos adicionales', 'lealez' ),
                    __( 'Sitio web', 'lealez' ),
                    __( 'Reservas, pedidos, chat y otros enlaces cuando Google los admite', 'lealez' ),
                ),
                'local_fields' => array(
                    __( 'Redes sociales y otros canales que Lealez conserva como información complementaria', 'lealez' ),
                ),
            ),
            'hours' => array(
                'label' => __( 'Horarios', 'lealez' ),
                'description' => __( 'Horario habitual y fechas especiales', 'lealez' ),
                'long_description' => __( 'Configura horarios normales y excepciones. Los cambios se guardan primero en Lealez y solo se publican cuando solicitas el envío.', 'lealez' ),
                'icon' => 'dashicons-clock',
                'group' => __( 'Perfil público', 'lealez' ),
                'scope' => 'google_write',
                'metabox_id' => 'oy_location_hours',
                'google_fields' => array(
                    __( 'Horario habitual, cierres y atención 24 horas', 'lealez' ),
                    __( 'Horarios especiales y excepciones por fecha', 'lealez' ),
                ),
            ),
            'attributes' => array(
                'label' => __( 'Características del negocio', 'lealez' ),
                'description' => __( 'Accesibilidad, servicios y comodidades', 'lealez' ),
                'long_description' => __( 'Google ofrece características distintas según la categoría y el país. Lealez consulta las opciones compatibles para esta ubicación antes de permitir su publicación.', 'lealez' ),
                'icon' => 'dashicons-yes-alt',
                'group' => __( 'Perfil público', 'lealez' ),
                'scope' => 'google_write',
                'metabox_id' => 'oy_location_gmb_more_attrs',
                'google_fields' => array( __( 'Características disponibles para la categoría y el país de la ubicación', 'lealez' ) ),
            ),
            'media' => array(
                'label' => __( 'Fotos', 'lealez' ),
                'description' => __( 'Contenido visual publicado', 'lealez' ),
                'long_description' => __( 'Consulta las fotografías asociadas a la ficha y abre cada recurso para revisarlo.', 'lealez' ),
                'icon' => 'dashicons-format-gallery',
                'group' => __( 'Contenido', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb_owner_media',
                'read_fields' => array( __( 'Fotos publicadas, tipo de contenido y fecha disponible', 'lealez' ) ),
            ),
            'menu' => array(
                'label' => __( 'Menú', 'lealez' ),
                'description' => __( 'Secciones, platos, precios y fotos', 'lealez' ),
                'long_description' => __( 'Disponible cuando Google confirma que la ubicación puede administrar un menú. Los cambios se guardan localmente antes de enviarse.', 'lealez' ),
                'icon' => 'dashicons-food',
                'group' => __( 'Contenido', 'lealez' ),
                'scope' => 'google_write',
                'metabox_id' => 'oy_location_menu',
                'google_fields' => array( __( 'Secciones, platos, precios, descripciones y medios compatibles', 'lealez' ) ),
            ),
            'services' => array(
                'label' => __( 'Servicios y catálogo', 'lealez' ),
                'description' => __( 'Oferta disponible para esta ubicación', 'lealez' ),
                'long_description' => __( 'Lealez muestra este módulo cuando la ficha dispone de información de servicios o catálogo. La integración actual informa claramente cuándo solo puede importar o guardar información local.', 'lealez' ),
                'icon' => 'dashicons-store',
                'group' => __( 'Contenido', 'lealez' ),
                'scope' => 'mixed',
                'metabox_id' => 'oy_location_products',
                'classic_save' => true,
                'read_fields' => array( __( 'Servicios o catálogo obtenidos desde Google cuando están disponibles', 'lealez' ) ),
                'local_fields' => array( __( 'Cambios locales cuando la integración disponible no permite publicarlos de forma segura', 'lealez' ) ),
            ),
            'posts' => array(
                'label' => __( 'Publicaciones', 'lealez' ),
                'description' => __( 'Novedades, ofertas y contenido', 'lealez' ),
                'long_description' => __( 'Consulta, crea, actualiza o elimina publicaciones de la ficha utilizando el flujo disponible de Google Business Profile.', 'lealez' ),
                'icon' => 'dashicons-megaphone',
                'group' => __( 'Contenido', 'lealez' ),
                'scope' => 'google_direct',
                'metabox_id' => 'oy_location_gmb_posts',
                'google_fields' => array( __( 'Publicaciones, llamadas a la acción, fechas y medios', 'lealez' ) ),
                'local_fields' => array( __( 'Borradores hasta que se ordena publicar', 'lealez' ) ),
            ),
            'reviews' => array(
                'label' => __( 'Opiniones', 'lealez' ),
                'description' => __( 'Reseñas y respuestas', 'lealez' ),
                'long_description' => __( 'Consulta reseñas y administra las respuestas del negocio.', 'lealez' ),
                'icon' => 'dashicons-star-filled',
                'group' => __( 'Interacción', 'lealez' ),
                'scope' => 'google_direct',
                'metabox_id' => 'oy_location_gmb_reviews',
                'read_fields' => array( __( 'Calificaciones, comentarios y fecha de las reseñas', 'lealez' ) ),
                'google_fields' => array( __( 'Respuestas del negocio', 'lealez' ) ),
            ),
            'performance' => array(
                'label' => __( 'Rendimiento', 'lealez' ),
                'description' => __( 'Interacciones con la ficha', 'lealez' ),
                'long_description' => __( 'Consulta los indicadores disponibles de rendimiento y conserva históricos para comparación dentro de Lealez.', 'lealez' ),
                'icon' => 'dashicons-chart-area',
                'group' => __( 'Resultados', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb_performance',
                'read_fields' => array( __( 'Visualizaciones, llamadas, clics, indicaciones, reservas y otros indicadores disponibles', 'lealez' ) ),
                'local_fields' => array( __( 'Históricos guardados para comparación y diagnóstico', 'lealez' ) ),
            ),
            'keywords' => array(
                'label' => __( 'Búsquedas', 'lealez' ),
                'description' => __( 'Cómo encuentran tu ubicación', 'lealez' ),
                'long_description' => __( 'Consulta las frases con las que los usuarios encontraron la ubicación y conserva los resultados seleccionados.', 'lealez' ),
                'icon' => 'dashicons-search',
                'group' => __( 'Resultados', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb_keywords',
                'read_fields' => array( __( 'Frases e impresiones mensuales disponibles', 'lealez' ) ),
                'local_fields' => array( __( 'Selección e histórico para reportes de Lealez', 'lealez' ) ),
            ),
            'busyhours' => array(
                'label' => __( 'Mayor interés', 'lealez' ),
                'description' => __( 'Tendencia por día y hora', 'lealez' ),
                'long_description' => __( 'Visualiza una estimación del patrón de interés construida a partir de los indicadores disponibles para la ubicación.', 'lealez' ),
                'icon' => 'dashicons-chart-bar',
                'group' => __( 'Resultados', 'lealez' ),
                'scope' => 'google_read',
                'metabox_id' => 'oy_location_gmb_busyhours',
                'read_fields' => array( __( 'Indicadores utilizados para calcular la tendencia', 'lealez' ) ),
                'local_fields' => array( __( 'Curva e índice estimado de mayor interés', 'lealez' ) ),
            ),
            'connection' => array(
                'label' => __( 'Vinculación con Google', 'lealez' ),
                'description' => __( 'Diagnóstico de la propiedad vinculada', 'lealez' ),
                'long_description' => __( 'Vista técnica para administradores del sitio. Los clientes ven únicamente el estado de conexión necesario para gestionar su ficha.', 'lealez' ),
                'icon' => 'dashicons-admin-links',
                'group' => __( 'Administración técnica', 'lealez' ),
                'scope' => 'system',
                'metabox_id' => 'oy_location_gmb',
                'site_admin_only' => true,
                'read_only' => true,
                'read_fields' => array( __( 'Estado de vinculación, verificación y datos técnicos de soporte', 'lealez' ) ),
            ),
            'sync' => array(
                'label' => __( 'Diagnóstico de sincronización', 'lealez' ),
                'description' => __( 'Límites, procesos e historial técnico', 'lealez' ),
                'long_description' => __( 'Herramientas técnicas para soporte y administración del sitio. No forman parte de la experiencia del cliente.', 'lealez' ),
                'icon' => 'dashicons-update',
                'group' => __( 'Administración técnica', 'lealez' ),
                'scope' => 'system',
                'metabox_id' => 'oy_gmb_integration_control',
                'site_admin_only' => true,
                'classic_save' => true,
            ),
        );
    }
}
