<?php
/** Unified location profile: modules. @package Lealez */
if ( ! defined( 'ABSPATH' ) ) { exit; }

trait Lealez_Unified_Location_Modules_Trait {

    private function get_location_modules() {
            return array(
                'overview' => array(
                    'label' => __( 'Resumen', 'lealez' ),
                    'description' => __( 'Estado completo del perfil', 'lealez' ),
                    'long_description' => __( 'Estado local, vinculación con Google y publicaciones pendientes.', 'lealez' ),
                    'icon' => 'dashicons-dashboard',
                    'group' => __( 'General', 'lealez' ),
                    'scope' => 'mixed',
                    'metabox_id' => '',
                ),
                'internal' => array(
                    'label' => __( 'Administración interna', 'lealez' ),
                    'description' => __( 'Empresa, lealtad y responsables', 'lealez' ),
                    'long_description' => __( 'Datos administrativos de Lealez que no se envían ni se publican en Google Business Profile.', 'lealez' ),
                    'icon' => 'dashicons-admin-settings',
                    'group' => __( 'General', 'lealez' ),
                    'scope' => 'internal',
                    'metabox_id' => '',
                    'local_fields' => array(
                        __( 'Empresa propietaria y nombre interno de la ficha', 'lealez' ),
                        __( 'Código y estado interno', 'lealez' ),
                        __( 'Configuración de lealtad', 'lealez' ),
                        __( 'Responsable, teléfonos, correos y notas internas', 'lealez' ),
                    ),
                ),
                'connection' => array(
                    'label' => __( 'Vinculación con Google', 'lealez' ),
                    'description' => __( 'Propiedad e identificadores', 'lealez' ),
                    'long_description' => __( 'Consulta la propiedad de Google vinculada. La asociación se protege para evitar enlaces duplicados o accidentales.', 'lealez' ),
                    'icon' => 'dashicons-admin-links',
                    'group' => __( 'General', 'lealez' ),
                    'scope' => 'system',
                    'metabox_id' => 'oy_location_gmb',
                    'business_admin_only' => true,
                    'read_only' => true,
                    'read_fields' => array( __( 'Account ID, Location ID, código de tienda y estado de verificación', 'lealez' ) ),
                ),
                'sync' => array(
                    'label' => __( 'Sincronización y estado', 'lealez' ),
                    'description' => __( 'Sync total, límites y log', 'lealez' ),
                    'long_description' => __( 'Orquesta la actualización de los módulos, respeta límites y conserva el historial técnico.', 'lealez' ),
                    'icon' => 'dashicons-update',
                    'group' => __( 'General', 'lealez' ),
                    'scope' => 'system',
                    'metabox_id' => 'oy_gmb_integration_control',
                    'business_admin_only' => true,
                    'classic_save' => true,
                ),
                'basic' => array(
                    'label' => __( 'Información básica', 'lealez' ),
                    'description' => __( 'Descripción, apertura y categorías', 'lealez' ),
                    'long_description' => __( 'Información pública principal de la ubicación y datos complementarios locales.', 'lealez' ),
                    'icon' => 'dashicons-info-outline',
                    'group' => __( 'Perfil', 'lealez' ),
                    'scope' => 'mixed',
                    'metabox_id' => 'oy_location_basic_info',
                    'google_fields' => array(
                        __( 'Descripción de la empresa', 'lealez' ),
                        __( 'Fecha de apertura', 'lealez' ),
                    ),
                    'local_fields' => array(
                        __( 'Categoría principal y categorías adicionales mientras no exista homologación segura del push', 'lealez' ),
                        __( 'Rango de precios', 'lealez' ),
                    ),
                ),
                'address' => array(
                    'label' => __( 'Dirección y áreas', 'lealez' ),
                    'description' => __( 'Dirección, servicio y mapa', 'lealez' ),
                    'long_description' => __( 'Administra la dirección pública, áreas de servicio y coordenadas que se envían a Google para validación.', 'lealez' ),
                    'icon' => 'dashicons-location',
                    'group' => __( 'Perfil', 'lealez' ),
                    'scope' => 'google_write',
                    'metabox_id' => 'oy_location_address',
                    'google_fields' => array(
                        __( 'Dirección y complemento', 'lealez' ),
                        __( 'Ciudad, región, país y código postal', 'lealez' ),
                        __( 'Áreas de servicio y visibilidad de la dirección', 'lealez' ),
                        __( 'Coordenadas y ubicación en el mapa', 'lealez' ),
                    ),
                ),
                'contact' => array(
                    'label' => __( 'Contacto y enlaces', 'lealez' ),
                    'description' => __( 'Teléfonos, web, chat y acciones', 'lealez' ),
                    'long_description' => __( 'Administra los canales públicos compatibles con Google y conserva los datos manuales que no forman parte del push.', 'lealez' ),
                    'icon' => 'dashicons-phone',
                    'group' => __( 'Perfil', 'lealez' ),
                    'scope' => 'mixed',
                    'metabox_id' => 'oy_location_contact',
                    'google_fields' => array(
                        __( 'Teléfono principal y teléfonos adicionales', 'lealez' ),
                        __( 'Sitio web', 'lealez' ),
                        __( 'Chat, reservas, pedidos y enlace de menú cuando Google lo admite', 'lealez' ),
                    ),
                    'local_fields' => array(
                        __( 'Redes sociales manuales y campos que el propio módulo identifique como locales', 'lealez' ),
                    ),
                ),
                'hours' => array(
                    'label' => __( 'Horarios', 'lealez' ),
                    'description' => __( 'Horario regular y especial', 'lealez' ),
                    'long_description' => __( 'Configura horarios normales y fechas especiales, envíalos a Google y verifica su aplicación.', 'lealez' ),
                    'icon' => 'dashicons-clock',
                    'group' => __( 'Perfil', 'lealez' ),
                    'scope' => 'google_write',
                    'metabox_id' => 'oy_location_hours',
                    'google_fields' => array(
                        __( 'Horario regular, cierres y atención 24 horas', 'lealez' ),
                        __( 'Horarios especiales y excepciones por fecha', 'lealez' ),
                    ),
                ),
                'attributes' => array(
                    'label' => __( 'Atributos “Más”', 'lealez' ),
                    'description' => __( 'Accesibilidad y características', 'lealez' ),
                    'long_description' => __( 'Gestiona los atributos permitidos para la categoría y publica únicamente las diferencias locales.', 'lealez' ),
                    'icon' => 'dashicons-yes-alt',
                    'group' => __( 'Perfil', 'lealez' ),
                    'scope' => 'google_write',
                    'metabox_id' => 'oy_location_gmb_more_attrs',
                    'google_fields' => array( __( 'Atributos dinámicos habilitados por Google para la categoría', 'lealez' ) ),
                ),
                'media' => array(
                    'label' => __( 'Fotos del propietario', 'lealez' ),
                    'description' => __( 'Biblioteca de Google', 'lealez' ),
                    'long_description' => __( 'Consulta las fotografías asociadas al perfil y abre cada recurso en Google.', 'lealez' ),
                    'icon' => 'dashicons-format-gallery',
                    'group' => __( 'Contenido', 'lealez' ),
                    'scope' => 'google_read',
                    'metabox_id' => 'oy_location_gmb_owner_media',
                    'read_fields' => array( __( 'Fotos, categorías de medios, fechas e identificadores devueltos por Google', 'lealez' ) ),
                ),
                'menu' => array(
                    'label' => __( 'Menú', 'lealez' ),
                    'description' => __( 'Secciones, productos y fotos', 'lealez' ),
                    'long_description' => __( 'Gestiona el menú de restaurantes, envía los cambios y verifica el resultado devuelto por Google.', 'lealez' ),
                    'icon' => 'dashicons-food',
                    'group' => __( 'Contenido', 'lealez' ),
                    'scope' => 'google_write',
                    'metabox_id' => 'oy_location_menu',
                    'google_fields' => array( __( 'Secciones, platos, precios, descripciones y medios compatibles', 'lealez' ) ),
                ),
                'services' => array(
                    'label' => __( 'Servicios', 'lealez' ),
                    'description' => __( 'Catálogo para no restaurantes', 'lealez' ),
                    'long_description' => __( 'Administra el catálogo local y sincroniza la información disponible desde Google; el módulo informa cuando la publicación no está disponible.', 'lealez' ),
                    'icon' => 'dashicons-store',
                    'group' => __( 'Contenido', 'lealez' ),
                    'scope' => 'mixed',
                    'metabox_id' => 'oy_location_products',
                    'classic_save' => true,
                    'read_fields' => array( __( 'Servicios obtenidos desde Google cuando el endpoint responde', 'lealez' ) ),
                    'local_fields' => array( __( 'Catálogo local cuando Google no ofrece un endpoint de publicación disponible', 'lealez' ) ),
                ),
                'posts' => array(
                    'label' => __( 'Publicaciones', 'lealez' ),
                    'description' => __( 'Posts y borradores', 'lealez' ),
                    'long_description' => __( 'Consulta, crea, actualiza o elimina publicaciones directamente en Google Business Profile.', 'lealez' ),
                    'icon' => 'dashicons-megaphone',
                    'group' => __( 'Interacción', 'lealez' ),
                    'scope' => 'google_direct',
                    'metabox_id' => 'oy_location_gmb_posts',
                    'google_fields' => array( __( 'Publicaciones, llamadas a la acción, fechas y medios', 'lealez' ) ),
                    'local_fields' => array( __( 'Borradores locales hasta que se ordena publicar', 'lealez' ) ),
                ),
                'reviews' => array(
                    'label' => __( 'Opiniones', 'lealez' ),
                    'description' => __( 'Reseñas y respuestas', 'lealez' ),
                    'long_description' => __( 'Consulta reseñas y publica o elimina respuestas del propietario directamente en Google.', 'lealez' ),
                    'icon' => 'dashicons-star-filled',
                    'group' => __( 'Interacción', 'lealez' ),
                    'scope' => 'google_direct',
                    'metabox_id' => 'oy_location_gmb_reviews',
                    'read_fields' => array( __( 'Calificaciones, comentarios y datos de reseñas', 'lealez' ) ),
                    'google_fields' => array( __( 'Respuestas del propietario', 'lealez' ) ),
                ),
                'performance' => array(
                    'label' => __( 'Rendimiento', 'lealez' ),
                    'description' => __( 'Métricas y comparativas', 'lealez' ),
                    'long_description' => __( 'Consulta las métricas de Business Profile Performance API y conserva snapshots locales.', 'lealez' ),
                    'icon' => 'dashicons-chart-area',
                    'group' => __( 'Analítica', 'lealez' ),
                    'scope' => 'google_read',
                    'metabox_id' => 'oy_location_gmb_performance',
                    'read_fields' => array( __( 'Impresiones, llamadas, clics, indicaciones, reservas y demás métricas disponibles', 'lealez' ) ),
                    'local_fields' => array( __( 'Snapshots guardados para comparación y diagnóstico', 'lealez' ) ),
                ),
                'keywords' => array(
                    'label' => __( 'Frases de búsqueda', 'lealez' ),
                    'description' => __( 'Keywords mensuales', 'lealez' ),
                    'long_description' => __( 'Consulta las frases con las que los usuarios encontraron la ubicación y guarda los resultados seleccionados.', 'lealez' ),
                    'icon' => 'dashicons-search',
                    'group' => __( 'Analítica', 'lealez' ),
                    'scope' => 'google_read',
                    'metabox_id' => 'oy_location_gmb_keywords',
                    'read_fields' => array( __( 'Frases e impresiones mensuales obtenidas de Google', 'lealez' ) ),
                    'local_fields' => array( __( 'Selección y caché para reportes de Lealez', 'lealez' ) ),
                ),
                'busyhours' => array(
                    'label' => __( 'Mayor interés', 'lealez' ),
                    'description' => __( 'Índice por día y hora', 'lealez' ),
                    'long_description' => __( 'Calcula el patrón de interés desde Performance API y conserva la distribución estimada en Lealez.', 'lealez' ),
                    'icon' => 'dashicons-chart-bar',
                    'group' => __( 'Analítica', 'lealez' ),
                    'scope' => 'google_read',
                    'metabox_id' => 'oy_location_gmb_busyhours',
                    'read_fields' => array( __( 'Métricas de Google utilizadas para el cálculo', 'lealez' ) ),
                    'local_fields' => array( __( 'Curva e índice estimado de mayor interés', 'lealez' ) ),
                ),
            );
        }
}
